services:
  # Services
  webserver:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - website
  mongo:
    image: mongo:4-bionic
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    profiles:
      - website
      - bot

  # Our shitcode
  bot:
    user: ${USER_ID}:${GROUP_ID}
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PACKAGE_NAME: boat
    image: powercord-boat
    working_dir: /opt/porkord/packages/boat
    command: pnpm run dev
    ports:
      - 4567:4567
    volumes:
      - ./packages/boat/src:/opt/porkord/packages/boat/src
      - ./packages/boat/dist:/opt/porkord/packages/boat/dist
      - ./packages/boat/package.json:/opt/porkord/packages/boat/package.json
      - ./packages/boat/tsconfig.json:/opt/porkord/packages/boat/tsconfig.json
      - ./config.json:/opt/porkord/config.json
    profiles:
      - bot
  api:
    user: ${USER_ID}:${GROUP_ID}
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PACKAGE_NAME: api
    image: powercord-api
    working_dir: /opt/porkord/packages/api
    command: pnpm run dev
    volumes:
      - settings-data:/var/lib/powercord
      - ./packages/types:/opt/porkord/packages/types
      - ./packages/api/src:/opt/porkord/packages/api/src
      - ./packages/api/dist:/opt/porkord/packages/api/dist
      - ./packages/api/package.json:/opt/porkord/packages/api/package.json
      - ./packages/api/tsconfig.json:/opt/porkord/packages/api/tsconfig.json
      - ./documentation:/opt/porkord/documentation
      - ./config.json:/opt/porkord/config.json
    profiles:
      - website
  web:
    user: ${USER_ID}:${GROUP_ID}
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PACKAGE_NAME: web
    image: powercord-web
    command: pnpm run dev -- --host
    working_dir: /opt/porkord/packages/web
    volumes:
      - ./packages/web:/opt/porkord/packages/web
    profiles:
      - website

volumes:
  db-data:
    driver: local
  settings-data:
    driver: local
